# Generated by Django 5.2.15 on 2026-07-02 02:08

import dirtyfields.dirtyfields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_brand_productstate_item_brand_installationrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaProductoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_id', models.CharField(db_index=True, max_length=40)),
                ('file', models.FileField(upload_to='recepciones/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_producto_adjuntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'adjunto de entrada',
                'verbose_name_plural': 'adjuntos de entrada',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_id', models.CharField(db_index=True, max_length=40)),
                ('tipo', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado/Reparación')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seriales', models.JSONField(blank=True, default=list)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventory.category')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventory.brand')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventory.productmodel')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventory.location')),
            ],
            options={
                'verbose_name': 'entrada de producto',
                'verbose_name_plural': 'entradas de producto',
                'ordering': ['-fecha_recepcion', '-id'],
                'indexes': [models.Index(fields=['reception_id', '-fecha_recepcion'], name='inventory_e_recepti_e3aaa9_idx'), models.Index(fields=['tipo', '-fecha_recepcion'], name='inventory_e_tipo_9b45b2_idx'), models.Index(fields=['marca', 'modelo', '-fecha_recepcion'], name='inventory_e_marca_i_5f3a84_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
