# Generated by Django 5.2.15 on 2026-07-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_entradaproductoattachment_entradaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='entregado_por_apellido',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='entregado_por_cedula',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='entregado_por_nombre',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproducto',
            name='entregado_por_rango_cargo',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaproductoattachment',
            name='attachment_type',
            field=models.CharField(choices=[('foto', 'Foto evidencia'), ('documento', 'Documento'), ('comprobante_firmado', 'Comprobante firmado')], default='documento', max_length=30),
        ),
    ]
