# Generated by Django 5.2.15 on 2026-07-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_entradaproducto_entregado_por_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaproducto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventory.location'),
        ),
    ]
