# Generated by Django 5.2.15 on 2026-07-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_entradaproducto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproducto',
            name='base_product',
            field=models.ForeignKey(blank=True, help_text='Producto base registrado al que corresponde esta recepción.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_producto', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_base_product',
            field=models.BooleanField(default=True, help_text='Indica si este artículo forma parte del catálogo base para recepción, instalación, reparación y servicios.'),
        ),
    ]
