# Generated by Django 5.2.15 on 2026-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_entradaproducto_base_product_item_is_base_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationrecord',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='installationrecord',
            name='state_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
