# Generated by Django 5.2.15 on 2026-08-05 02:57

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import IntegrityError


def populate_unit_measure_data(apps, schema_editor):
    Item = apps.get_model('inventory', 'Item')
    UnitMeasure = apps.get_model('inventory', 'UnitMeasure')

    defaults = [
        ('und', 'Unidad', 'Unidad base'),
        ('par', 'Par', 'Par'),
        ('juego', 'Juego', 'Juego'),
        ('metro', 'Metro', 'Metro'),
        ('litro', 'Litro', 'Litro'),
        ('kg', 'Kilogramo', 'Kilogramo'),
        ('set', 'Set', 'Set'),
        ('pza', 'Pieza', 'Pieza'),
    ]

    created_units = {}
    for code, name, description in defaults:
        unit, _ = UnitMeasure.objects.get_or_create(code=code, defaults={'name': name, 'description': description})
        created_units[code] = unit

    def get_unit_from_value(value):
        if value in (None, ''):
            return None
        raw = str(value).strip().lower()
        if not raw:
            return None
        if raw in created_units:
            return created_units[raw]
        code = raw[:30]
        existing = UnitMeasure.objects.filter(code=code).first()
        if existing:
            created_units[raw] = existing
            return existing
        existing_name = UnitMeasure.objects.filter(name__iexact=raw.title()).first()
        if existing_name:
            created_units[raw] = existing_name
            return existing_name
        suffix = 1
        while True:
            candidate_code = f'{code[:24]}-{suffix}' if len(code) > 24 else f'{code}-{suffix}'
            candidate = UnitMeasure.objects.filter(code=candidate_code).first()
            if not candidate:
                unit = UnitMeasure.objects.create(code=candidate_code, name=raw.title(), description='Unidad migrada')
                created_units[raw] = unit
                return unit
            suffix += 1

    for item in Item.objects.iterator():
        unit = get_unit_from_value(getattr(item, 'unit', None))
        if unit is None:
            continue
        item.unit_new_id = unit.id
        item.save(update_fields=['unit_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_repair_installationrecord_state_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='unit_new',
            field=models.ForeignKey(blank=True, help_text='Unidad de medida del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.unitmeasure'),
        ),
        migrations.RunPython(populate_unit_measure_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='unit_new',
            new_name='unit',
        ),
    ]
