# Generated by Django 5.2.15 on 2026-08-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_unitmeasure_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unidad de medida del producto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unitmeasure'),
        ),
    ]
