# Generated by Django 5.2.15 on 2026-07-16 13:24

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_entradaproducto_ubicacion'),
        ('workorders', '0007_remove_workorderpart_work_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(editable=False, help_text='Número correlativo del servicio (formato SRV-YYYY-XXXXX)', max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('reparacion', 'Reparación'), ('instalacion', 'Instalación'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('equipment_condition', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], default='usado', max_length=10)),
                ('equipment_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('equipment_brand_snapshot', models.CharField(blank=True, max_length=100)),
                ('equipment_model_snapshot', models.CharField(blank=True, max_length=100)),
                ('equipment_description_snapshot', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recibido', 'Recibido'), ('en_diagnostico', 'En diagnóstico'), ('en_proceso', 'En proceso'), ('pendiente_repuesto', 'Pendiente repuesto'), ('completado', 'Completado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=25)),
                ('diagnosis', models.TextField(blank=True)),
                ('work_performed', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, help_text='Técnico responsable del servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_orders', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(help_text='Equipo previamente registrado en inventario', on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='inventory.item')),
                ('unit', models.ForeignKey(blank=True, help_text='Unidad o dependencia solicitante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='inventory.location')),
            ],
            options={
                'verbose_name': 'orden de servicio',
                'verbose_name_plural': 'órdenes de servicio',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['service_type', 'status'], name='workorders__service_f8a4ce_idx'), models.Index(fields=['assigned_technician', 'status'], name='workorders__assigne_781f1d_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
