# Generated by Django 5.2.15 on 2026-07-16 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_serviceorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='note', max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(blank=True, max_length=25)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_order_logs', to=settings.AUTH_USER_MODEL)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workorders.serviceorder')),
            ],
            options={
                'verbose_name': 'bitácora de orden de servicio',
                'verbose_name_plural': 'bitácoras de órdenes de servicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
