# Generated by Django 5.2.15 on 2026-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0009_serviceorderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='equipment_serial_number',
            field=models.CharField(blank=True, help_text='Número de serial del equipo específico recibido para servicio.', max_length=100),
        ),
    ]
