# Generated by Django 5.2.15 on 2026-07-18 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_installationrecord_serial_number_and_more'),
        ('workorders', '0010_serviceorder_equipment_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('equipment_condition', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], default='usado', max_length=10)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('item_brand_snapshot', models.CharField(blank=True, max_length=100)),
                ('item_model_snapshot', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(help_text='Producto base registrado incluido en esta orden.', on_delete=django.db.models.deletion.PROTECT, related_name='service_order_items', to='inventory.item')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.serviceorder')),
            ],
            options={
                'verbose_name': 'línea de orden de servicio',
                'verbose_name_plural': 'líneas de orden de servicio',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['service_order', 'equipment_condition'], name='workorders__service_ed9b32_idx'), models.Index(fields=['serial_number'], name='workorders__serial__3c2c9d_idx')],
            },
        ),
    ]
