# Generated by Django 5.2.15 on 2026-07-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_installationrecord_serial_number_and_more'),
        ('workorders', '0011_serviceorderitem'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='serviceorderitem',
            constraint=models.UniqueConstraint(fields=('service_order', 'item', 'serial_number'), name='uniq_service_order_item_serial'),
        ),
    ]
