# Generated by Django 5.2.15 on 2026-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_serviceorderitem_uniq_service_order_item_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='recipient_first_name',
            field=models.CharField(blank=True, help_text='Nombre de la persona para quien se realiza la orden (opcional).', max_length=120),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='recipient_id_card',
            field=models.CharField(blank=True, help_text='Cédula/identificación de la persona para quien se realiza la orden (opcional).', max_length=30),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='recipient_last_name',
            field=models.CharField(blank=True, help_text='Apellido de la persona para quien se realiza la orden (opcional).', max_length=120),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='recipient_rank_position',
            field=models.CharField(blank=True, help_text='Rango o cargo de la persona para quien se realiza la orden (opcional).', max_length=120),
        ),
    ]
