# Generated by Django 5.2.15 on 2026-08-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0014_despachoattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='signed_receipt',
            field=models.FileField(blank=True, help_text='Comprobante de cierre firmado por el destinatario.', null=True, upload_to='service_orders/signed_receipts/%Y/%m/%d/'),
        ),
    ]
